### ISSUE TITLE
Regions listed instead of countries.

### ISSUE THREAD

**Issue by HarleyFuagras** [petercoles/Multilingual-Country-List#3]
I have detected that not only countries are being listed but also some regions belonging to countries such as Canary Islands or Ceuta & Melilla wich are part of Spain. Is there any way to avoid this and list only countries? Thank you very much.

**Comment by petercoles** [comment]
If it's a newly-recognised country, check that it's not available in the latest release,a s I've just refreshed the data.

Otherwise, the package returns a collection so you can "put" additional items into the collection. For example: ```Countries::lookup()->put('ZZ', 'My Country')->sort();```

**Comment by petercoles** [comment]
The underlying list is the internationally recognised one, so I don't want to make (and then have to maintain) changes to that, but I see your point. There are politics involved in deciding what to include and sometimes that leads to undesirable results.

However, this package returns a highly manipulable collection. So for the example you've given, you could simply remove Canary Islands and Ceuta & Melilla from the results as follows:
```
Countries::lookup()->reject(function($country, $key) {
    return in_array($key, [ 'IC', 'TD' ]);
});
```
